# action.yml
name: 'Save to Software Heritage'
icon: save
color: green
description: 'Saves the repository to the Software Heritage Archive'
outputs:
  result: # id of output
    description: 'Result of call to Software Heritage API'
runs:
  using: 'docker'
  image: 'Dockerfile'
