on: [push]

jobs:
  swh-save:
    runs-on: ubuntu-latest
    name: Saves this repo to SWH
    steps:
    - name: Save step
      id: save
      uses: sdruskat/swh-save-action@main
    # Use the output from the `hello` step
    - name: Print result
      run: echo "The result from the API call was ${{ steps.save.outputs.result }}"
